# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "l1"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["staticlib"]

[dependencies]
num = "0.4"
static_fir = "0.2.0"
